version: "3.8"
services:
  mosquitto:
    container_name: mosquitto
    image: eclipse-mosquitto:latest
    restart: always
    deploy:
      resources:
        limits:
          memory: 256M
    security_opt:
      - no-new-privileges:true
#    volumes:
#      - /home/ubuntu/docker/mosquitto/config/mosquitto.conf:/mosquitto/config/mosquitto.conf
#      - /home/ubuntu/docker/mosquitto/config/pwfile:/mosquitto/config/pwfile
#      - /home/ubuntu/docker/mosquitto/data:/mosquitto/data
#      - /home/ubuntu/docker/mosquitto/log:/mosquitto/log
    ports:
      - "1884:1883"
      - "9001:9001"

